### ISSUE TITLE
Support arguements for custom shell

### ISSUE THREAD

**Issue by colinyip** [UnitedIncome/serverless-shell#2]
Would be great to support arguments for custom shell as well. I want to be able to execute `rlwrap --always-readline babel-node` instead of `babel-node`

It should work if we set shell to true when the child process is spawned. 
https://github.com/UnitedIncome/serverless-shell/blob/master/index.js#L110
```
this.serverless.cli.log(`Spawning ${shellBinary}...`);
      spawnSync(shellBinary, [], {
        env: process.env,
        stdio: 'inherit',
        shell: true
      });
```

Thanks!

**Comment by dschep** [comment]
Done!
